# This file was generated by GoReleaser. DO NOT EDIT.
cask "zqta" do
  desc "ZQTA project."
  homepage "https://github.com/VinCSS-Public-Projects/ZQTA"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zqta"

  on_macos do
    on_intel do
      url "https://github.com/VinCSS-Public-Projects/ZQTA/releases/download/v1.0.0/zqta_v1.0.0_darwin_amd64.tar.gz"
      sha256 "b282e998d1ce0745865dda7e27cb4409b267faea3e7a277d26d7a5666d94d7fa"
    end
    on_arm do
      url "https://github.com/VinCSS-Public-Projects/ZQTA/releases/download/v1.0.0/zqta_v1.0.0_darwin_arm64.tar.gz"
      sha256 "4704cfe81525d4b9db36d9f7444221d28ba095b7e9ca4b992f1bd1b27397cf05"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/VinCSS-Public-Projects/ZQTA/releases/download/v1.0.0/zqta_v1.0.0_linux_amd64.tar.gz"
      sha256 "2e3522b94342ba0ad706d05651d7c99c99c493d1c099c0f5c4c79e31bc672e69"
    end
    on_arm do
      url "https://github.com/VinCSS-Public-Projects/ZQTA/releases/download/v1.0.0/zqta_v1.0.0_linux_arm64.tar.gz"
      sha256 "527232e29ac355acf8d8e74fe2cb2878beecc9a14ba9bc9e0898998a2cbd9252"
    end
  end

  # No zap stanza required
end
