# This file was generated by GoReleaser. DO NOT EDIT.
cask "zqta" do
  desc "ZQTA project."
  homepage "https://github.com/VinCSS-Public-Projects/ZQTA"
  version "1.0.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zqta"

  on_macos do
    on_intel do
      url "https://github.com/VinCSS-Public-Projects/ZQTA/releases/download/v1.0.8/zqta_v1.0.8_darwin_amd64.tar.gz"
      sha256 "e0addcec4191e0743599b182f60ff98b06fb3d72907aa260c7e802e07b66e71c"
    end
    on_arm do
      url "https://github.com/VinCSS-Public-Projects/ZQTA/releases/download/v1.0.8/zqta_v1.0.8_darwin_arm64.tar.gz"
      sha256 "fbb389b24aa9c06e1bd1f93f8b5ecb9506557f1ce3d2591becc27c7933594e8d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/VinCSS-Public-Projects/ZQTA/releases/download/v1.0.8/zqta_v1.0.8_linux_amd64.tar.gz"
      sha256 "cd42eaf0b312dc464060f9f745be81fa10f99f1579342a7261acafb15462be6a"
    end
    on_arm do
      url "https://github.com/VinCSS-Public-Projects/ZQTA/releases/download/v1.0.8/zqta_v1.0.8_linux_arm64.tar.gz"
      sha256 "a5b6cc40a0dac7a913e137da8d212350762a6bfd04a2be284a5cd373d06360c7"
    end
  end

  # No zap stanza required
end
