# This file was generated by GoReleaser. DO NOT EDIT.
cask "zqta-ui" do
  desc ""
  homepage ""
  version "1.0.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zqta-ui"

  on_macos do
    on_intel do
      url "https://github.com/VinCSS-Public-Projects/ZQTA/releases/download/v1.0.5/zqta-ui_1.0.5_darwin_amd64.tar.gz"
      sha256 "d6e0589848102f95070af8d49a21dcad7b499ddf086893dd75c2daf7572ee081"
    end
    on_arm do
      url "https://github.com/VinCSS-Public-Projects/ZQTA/releases/download/v1.0.5/zqta-ui_1.0.5_darwin_arm64.tar.gz"
      sha256 "e509a15f50b86fb8d049e64800bbcfbf4429003c220e3372818f0f260714b80f"
    end
  end

  # No zap stanza required
end
