# This file was generated by GoReleaser. DO NOT EDIT.
cask "zqta-ui" do
  desc ""
  homepage ""
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zqta-ui"

  on_macos do
    on_intel do
      url "https://github.com/VinCSS-Public-Projects/ZQTA/releases/download/v1.0.0/zqta-ui_1.0.0_darwin_amd64.tar.gz"
      sha256 "3bb9888f3d49aec822d294ec519f67bbde59b23b9dc88aa380c7fe074630227f"
    end
    on_arm do
      url "https://github.com/VinCSS-Public-Projects/ZQTA/releases/download/v1.0.0/zqta-ui_1.0.0_darwin_arm64.tar.gz"
      sha256 "f9499a6a47875191a096aba1a046740dd5998fb2962e433e5321037384c72d1a"
    end
  end

  # No zap stanza required
end
