# This file was generated by GoReleaser. DO NOT EDIT.
cask "zqta" do
  desc "ZQTA project."
  homepage "https://github.com/VinCSS-Public-Projects/ZQTA"
  version "1.0.10"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zqta"

  on_macos do
    on_intel do
      url "https://github.com/VinCSS-Public-Projects/ZQTA/releases/download/v1.0.10/zqta_v1.0.10_darwin_amd64.tar.gz"
      sha256 "27a563e9e9f706847f9764b30ae8bc913c9eac17191b660f4b8c68870dd39fa1"
    end
    on_arm do
      url "https://github.com/VinCSS-Public-Projects/ZQTA/releases/download/v1.0.10/zqta_v1.0.10_darwin_arm64.tar.gz"
      sha256 "f0277e4e5c53f12daa630ea6010bb7ca44b08a77d9e9cb01c473b6a4b52e5ca7"
    end
  end

  # No zap stanza required
end
