# This file was generated by GoReleaser. DO NOT EDIT.
cask "zqta" do
  desc "ZQTA project."
  homepage "https://github.com/VinCSS-Public-Projects/ZQTA"
  version "1.0.10"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zqta"

  on_macos do
    on_intel do
      url "https://github.com/VinCSS-Public-Projects/ZQTA/releases/download/v1.0.10/zqta_v1.0.10_darwin_amd64.tar.gz"
      sha256 "61bd6541444efbad7a4ea0f259c5dc7e12571d4e7bb41cf73025416a64eb18a7"
    end
    on_arm do
      url "https://github.com/VinCSS-Public-Projects/ZQTA/releases/download/v1.0.10/zqta_v1.0.10_darwin_arm64.tar.gz"
      sha256 "c3c105b545401e0ebd349afd40c3cab09bbb34f5b88aeb7bba765b5610e9df3d"
    end
  end

  # No zap stanza required
end
