# This file was generated by GoReleaser. DO NOT EDIT.
cask "zqta-ui" do
  desc ""
  homepage ""
  version "1.0.10"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zqta-ui"

  on_macos do
    on_intel do
      url "https://github.com/VinCSS-Public-Projects/ZQTA/releases/download/v1.0.10/zqta-ui_v1.0.10_darwin_amd64.tar.gz"
      sha256 "bb69fefc6e85fc53aaae5c050cbca225895ef50afbd9aafb2de37e71b59d5610"
    end
    on_arm do
      url "https://github.com/VinCSS-Public-Projects/ZQTA/releases/download/v1.0.10/zqta-ui_v1.0.10_darwin_arm64.tar.gz"
      sha256 "cca1c59c9a7e8776c52dd0d9523b9f39afef547cd636158c9e4b03d9150e0be6"
    end
  end

  # No zap stanza required
end
