# This file was generated by GoReleaser. DO NOT EDIT.
cask "zqta" do
  desc "ZQTA project."
  homepage "https://github.com/VinCSS-Public-Projects/ZQTA"
  version "1.0.10"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zqta"

  on_macos do
    on_intel do
      url "https://github.com/VinCSS-Public-Projects/ZQTA/releases/download/v1.0.10/zqta_v1.0.10_darwin_amd64.tar.gz"
      sha256 "c89d518d0ab7a3e95cd4ca998ef7d7e24983573874560ffe9ca9d92abea00cc3"
    end
    on_arm do
      url "https://github.com/VinCSS-Public-Projects/ZQTA/releases/download/v1.0.10/zqta_v1.0.10_darwin_arm64.tar.gz"
      sha256 "2d23674f3b42779e75563727521db068a515ed49ae3fb5fd0b51cb287be48b18"
    end
  end

  # No zap stanza required
end
